### ISSUE TITLE
Adding nao.obs.nc to repo

### ISSUE THREAD

**Issue by hCraker** [NCAR/geocat-datafiles#10]
This file is needed for https://github.com/NCAR/GeoCAT-examples/issues/284

**Comment by michaelavs** [comment]
@erogluorhan I've been looking through Glade for this file and I dont think it exists. The closest I could find (name wise, and even then not very similar) was "NAO_b053.03_0000-0999.nc" in /glade/p/cisl/vast/ncldev/data/netcdf3. I also checked through /glade/p/cisl/vast/ncldev/test/ncargtest/nclscripts/cdf_files and a couple other various directories. Any ideas on other places to check for the file?

**Comment by michaelavs** [comment]
@hCraker It looks like that specific file isn't on the Glade server. If you are ok with it, I can add the similarly titled file that I mentioned to Orhan in the previous comment, or you may want to investigate if there is a different file with similar data to this one. Past those two options, we may be able to ask around and see if anyone knows where else it could be contained, but it may still arise that the file does not exist. Let me know what you would like to do and we can go from there!

**Comment by hCraker** [comment]
@michaelavs I haven't looked at the Glade server before, so I'm not sure how I could search through it for a file with similar data. For now, if you could add "NAO_b053.03_0000-0999.nc" to the repo that would be great. Thanks!

**Comment by michaelavs** [comment]
> @michaelavs I haven't looked at the Glade server before, so I'm not sure how I could search through it for a file with similar data. For now, if you could add "NAO_b053.03_0000-0999.nc" to the repo that would be great. Thanks!

Just tried to add that file and it looks like it already has been uploaded to the repo, so you can use it whenever you're ready!

**Comment by hCraker** [comment]
@michaelavs I have finally gotten some time to take a look at "NAO_b053.03_0000-0999.nc" and it looks like the data only has a `time` dimension. The data I'm looking for is spatial, so this isn't a suitable replacement file. I'm going to try a few different files that are already in this repository to see if I can find one for my purposes.

**Comment by michaelavs** [comment]
@hCraker Let me know if you find anything. I just tried to look directly at the NCL website as some datasets are available there, but the only one was again NAO_b053.03_0000-0999.nc. 

@clyne do you by chance know if there is anywhere else a dataset may be stored for an NCL example? We have looked on the GLADE server and through the NCL website but cannot find the correct file. The file is needed for [panel_9 ](https://www.ncl.ucar.edu/Applications/Scripts/panel_9.ncl)

**Comment by clyne** [comment]
Sorry, I do not.
