### ISSUE TITLE
GH Action still not working as expected

### ISSUE THREAD

**Issue by jukent** [NCAR/geocat-datafiles#52]
So the action is still failing to push to the `update-registry` branch. Possible reasons for this: the branch is not being recognized for some reason and we want to make a new branch that we can assert exists at the time of the action (and is unique because the new branch command will fail if repeated):
```

    - name: Commit changes
      if: steps.git-status.outputs.commit_needed == 'true'
      run: |
        git config --global user.name '${{ github.actor }}'
        git config --global user.email '<${{ github.actor }}@users.noreply.github.com>'
        git add registry.txt
        git commit --allow-empty -m "Update Registry.txt"
        git push --set-upstream origin "$(date +%Y%m%d)-$(uuidgen | cut -c -8)"

    - name: Create pull request
      if: steps.git-status.outputs.commit_needed == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        branch: "$(date +%Y%m%d)-$(uuidgen | cut -c -8)"
        commit-message: Update Registry.txt
        title: Update Registry.txt
        body: |
          This pull request updates the registry.txt file.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Or the action is failing because the `update-registry` branch is a few commits behind. Then we want to do a git fetch first:

```
    - name: Check for changes
      id: git-status
      run: |
        git status --porcelain > changes.txt
        if [ ! -s changes.txt ]; then
          echo "::set-output name=commit_needed::false"
        else
          echo "::set-output name=commit_needed::true"
        fi
      shell: bash

    - name: Fetch upstream
       if: steps.git-status.outputs.commit_needed == 'true'
      run: |
          git fetch origin
          git checkout update-registry
          git merge origin/update-registry

    - name: Commit changes
      if: steps.git-status.outputs.commit_needed == 'true'
      run: |
        git config --global user.name '${{ github.actor }}'
        git config --global user.email '<${{ github.actor }}@users.noreply.github.com>'
        git add registry.txt
        git commit --allow-empty -m "Update Registry.txt"
        git push origin update-registry

    - name: Create pull request
      if: steps.git-status.outputs.commit_needed == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        branch: update-registry
        commit-message: Update Registry.txt
        title: Update Registry.txt
        body: |
          This pull request updates the registry.txt file.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I like the second method because it creates less branches that we have to delete. So I'm going to try the bottom method first. Any ideas on this are appreciated!

**Comment by kafitzgerald** [comment]
Just stumbled upon this as I was cleaning up the issue backlog and docs.

@jukent is it worth closing this for now and maybe removing the broken GitHub Action?  

If I understand correctly, the purpose of this was to avoid having to update the registry file ourselves when contributing new files.  It seemed like it was a bit of a pain to implement in practice though and it's not that much trouble to do it manually as described in the contributing guide.  Maybe I'm missing some of the purpose/vision here though? 

In hindsight, I'm also a little worried about the tradeoffs here w/ the need to add additional tokens / permissions to get this done.

**Comment by jukent** [comment]
Yeah that sounds reasonable. When I started this anything seemed possible with GitHub actions haha. I'm sure I could look again and make progress, but ultimately we aren't making changes to the data files that frequently. This is high effort low reward/low priority.
